"""create competitions table

Revision ID: 6a6b5c537b66
Revises: 
Create Date: 2026-07-30 12:02:43.062335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6b5c537b66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('internal_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('association_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_association_id'), 'competitions', ['association_id'], unique=False)
    op.create_index(op.f('ix_competitions_internal_id'), 'competitions', ['internal_id'], unique=True)
    op.create_index(op.f('ix_competitions_season_id'), 'competitions', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitions_season_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_internal_id'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_association_id'), table_name='competitions')
    op.drop_table('competitions')
    # ### end Alembic commands ###
