"""create phases and competition groups

Revision ID: 81a1b54b04b8
Revises: 6a6b5c537b66
Create Date: 2026-07-30 12:19:01.467321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a1b54b04b8'
down_revision: Union[str, Sequence[str], None] = '6a6b5c537b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'phase_order', name='uq_phases_competition_id_phase_order')
    )
    op.create_index(op.f('ix_phases_competition_id'), 'phases', ['competition_id'], unique=False)
    op.create_table('competition_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('competition_level', sa.Integer(), nullable=False),
    sa.Column('fpf_competition_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'group_name', name='uq_competition_groups_phase_id_group_name')
    )
    op.create_index(op.f('ix_competition_groups_fpf_competition_id'), 'competition_groups', ['fpf_competition_id'], unique=False)
    op.create_index(op.f('ix_competition_groups_phase_id'), 'competition_groups', ['phase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_groups_phase_id'), table_name='competition_groups')
    op.drop_index(op.f('ix_competition_groups_fpf_competition_id'), table_name='competition_groups')
    op.drop_table('competition_groups')
    op.drop_index(op.f('ix_phases_competition_id'), table_name='phases')
    op.drop_table('phases')
    # ### end Alembic commands ###
